# Generated by Django 2.2 on 2022-01-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_auto_20220106_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='instructor',
            name='person_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses_app.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='person_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses_app.Person'),
            preserve_default=False,
        ),
    ]
